### ISSUE TITLE
CI Tests failing 

### ISSUE THREAD

**Issue by Genysys** [brave-experiments/Mjolnir#211]
## Description

The units tests are failing and i cannot immediately trace why. This is odd, as it also affects old successful commits.

The current output is:

```
Restoring env variables.
--- FAIL: TestApplyCmd_Run (0.38s)
    commands_test.go:386: 
                Error Trace:    commands_test.go:386
                Error:          Not equal: 
                                expected: 0
                                actual  : 4
```

This does not seem to affect the build the binary and running it.

## Possible Cause
- Some dependency might have changed. 

## Possible Actions

- Summon @nvonpentz 
- Continue debugging.

**Comment by Genysys** [comment]
## Update

It turns out that the test pass in travis:

### Output
```
Successfully wrote 331610 bytes to path terra/static.go 
go test -cover -covermode=count -coverprofile=coverage.out ./...
go: downloading github.com/stretchr/testify v1.4.0
go: extracting github.com/stretchr/testify v1.4.0
go: downloading github.com/pmezard/go-difflib v1.0.0
go: extracting github.com/pmezard/go-difflib v1.0.0
ok  	github.com/brave-experiments/Mjolnir	0.396s	coverage: 85.8% of statements
ok  	github.com/brave-experiments/Mjolnir/builder	0.070s	coverage: 22.6% of statements
ok  	github.com/brave-experiments/Mjolnir/connect	0.076s	coverage: 100.0% of statements
ok  	github.com/brave-experiments/Mjolnir/terra	0.921s	coverage: 91.5% of statements
The command "make test" exited with 0.
```

This leads  to the conlusions that it is either the symlinks added to make local development of the terraform development quicker by not having to build the binary every time a change was made, or some git egde case. 

The deployment phase of the travis  is still failing though. 


### Output 

```
home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/brave-experiments/Mjolnir/releases: 404 - Not Found // See: https://developer.github.com/v3/repos/releases/#create-a-release (Octokit::NotFound)
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.4/lib/faraday/connection.rb:175:in `post'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/connection.rb:28:in `post'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/client/releases.rb:32:in `create_release'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-releases-1.10.14/lib/dpl/provider/releases.rb:116:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.14/lib/dpl/provider.rb:199:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.14/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.14/lib/dpl/provider.rb:199:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.14/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.14/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.14/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `<main>'
failed to deploy
```
